apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: size-small
spec:
  cpu: "1"
  memory: "2Gi"
---

apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: pgconfig1
spec:
  postgresVersion: "16"
  postgresql.conf:
    shared_buffers: '512MB'
    random_page_cost: '1.5'
    password_encryption: 'scram-sha-256'
    log_checkpoints: 'on'

---

apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: my-cluster
spec:
  postgres:
    version: '16.1'
  instances: 2
  sgInstanceProfile: 'size-small'
  pods:
    persistentVolume:
      size: '10Gi'
  configurations:
    sgPostgresConfig: 'pgconfig1'
    backups:
    - sgObjectStorage: 'backupconfig1'
      cronSchedule: '*/5 * * * *'
      retention: 6
  prometheusAutobind: true
---
apiVersion: stackgres.io/v1beta1
kind: SGObjectStorage
metadata:
  name: backupconfig1
spec:
  type: s3Compatible
  s3Compatible:
    bucket: bucket-20240602-2126 
    region: eu-frankfurt-1
    enablePathStyleAddressing: true
    endpoint: "https://fradozn9lozb.compat.objectstorage.eu-frankfurt-1.oraclecloud.com"
    awsCredentials:
      secretKeySelectors:
        accessKeyId:
          key: accessKeyId
          name: oci-s3-credentials
        secretAccessKey:
          key: secretAccessKey
          name: oci-s3-credentials