apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part1-bitnami-primary-slave
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.4.0
    chart: postgresql
    helm:
      releaseName: main
      values: |
        readReplicas.replicaCount: 1
        metrics.enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: part1-bitnami-primary-slave
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true