# This simply does not work - problem with CRD and replace and also with 'main-init webhook'
# install as in stone ages:
#helm repo add stackgres-charts https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
#helm upgrade -install --create-namespace --namespace part5-stackgres-operator main stackgres-charts/stackgres-operator
# rendered here:
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part5-stackgres-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: argocd-gitops/apps/part5-stackgres-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: part5-stackgres-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: part5-stackgres-operator
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
#    targetRevision: 1.10.0
#    chart: stackgres-operator
#    helm:
#      releaseName: main
#      values: |
#        serviceAccount:
#          create: true
#
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: part5-stackgres-operator
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#    syncOptions:
#      - CreateNamespace=true
#      #- Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part5-stackgres-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: argocd-gitops/apps/part5-stackgres
  destination:
    server: https://kubernetes.default.svc
    namespace: part5-stackgres-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part5-stackgres-cp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: postgresql-data-loss-checker/helm
    helm:
      releaseName: primary
      values: |
        name: primary
        readOnly: "false"
        replicaCount: 2
        connection:
          host: my-cluster-primary
          secretName: my-cluster
          secretKey: superuser-password
          user: postgres
          dbname: postgres
          sslmode: disable
  destination:
    server: https://kubernetes.default.svc
    namespace: part5-stackgres-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part5-stackgres-cs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: postgresql-data-loss-checker/helm
    helm:
      releaseName: slave
      values: |
        name: slave
        readOnly: "true"
        replicaCount: 4
        connection:
          host: my-cluster-replicas
          secretName: my-cluster
          secretKey: superuser-password
          user: postgres
          dbname: postgres
          sslmode: disable
  destination:
    server: https://kubernetes.default.svc
    namespace: part5-stackgres-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true