apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part2-zalando
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    targetRevision: 1.11.0
    chart: postgres-operator
    helm:
      releaseName: main
      values: |

  destination:
    server: https://kubernetes.default.svc
    namespace: part2-zalando
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
# FIXME: separate dir for argo to startup
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: zalando
  namespace: part2-zalando
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    app: # or 'foo_user: []'

  #databases: name->owner
  databases:
    app: app
  postgresql:
    version: "16"