apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part1-bitnami-primary-slave
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.4.0
    chart: postgresql
    helm:
      releaseName: main
      values: |
        architecture: replication
        metrics.enabled: true
        readReplicas:
          replicaCount: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: part1-bitnami-primary-slave
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part1-bitnami-primary-slave-cp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: postgresql-data-loss-checker/helm
    helm:
      releaseName: primary
      values: |
        name: primary
        connection:
          host: main-postgresql-primary

  destination:
    server: https://kubernetes.default.svc
    namespace: part1-bitnami-primary-slave
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part1-bitnami-primary-slave-cs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: postgresql-data-loss-checker/helm
    helm:
      releaseName: slave
      values: |
        name: slave
        readOnly: "true"
        replicaCount: 3
        auth:
          postgresPassword: secretpassword
        connection:
          host: main-postgresql-read

  destination:
    server: https://kubernetes.default.svc
    namespace: part1-bitnami-primary-slave
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true