apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part5-stackgres-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
    targetRevision: 1.10.0
    chart: stackgres-operator
    helm:
      releaseName: main
      values: |
        serviceAccount:
          create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: part5-stackgres-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part5-stackgres-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: argocd-gitops/apps/part5-stackgres
  destination:
    server: https://kubernetes.default.svc
    namespace: part5-stackgres-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true