apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part1-bitnami-only-primary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.4.0
    chart: postgresql
    helm:
      releaseName: main
      # setting the fixed password was necessary as it kept changing even in the secret
      values: |
        readReplicas.replicaCount: 0
        metrics.enabled: true
        name: main
        auth:
          postgresPassword: secretpassword
  destination:
    server: https://kubernetes.default.svc
    namespace: part1-bitnami-only-primary
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part1-bitnami-only-primary-checker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/depeche-io/dbaas-postgresql.git
    targetRevision: main
    path: postgresql-data-loss-checker/helm
    helm:
      releaseName: main
      values: |
        name: primary
  destination:
    server: https://kubernetes.default.svc
    namespace: part1-bitnami-only-primary
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---

