apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.6.0
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          enabled: true

        grafana:
          enabled: true

        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false

        prometheus:
          ingress:

          prometheusSpec:
            resources:
             limits:
               cpu: 2000m
               memory: 2048Mi
             requests:
               cpu: 2000m
               memory: 2048Mi

        prometheusOperator:
          tls:
            enabled: false
          admissionWebhooks:
             failurePolicy: Ignore
             # FIXME: s timto v argocd selze
             enabled: false

        kubeApiServer:
          serviceMonitor:
            metricRelabelings:
              # Drop excessively noisy apiserver buckets.
              - action: drop
                regex: apiserver_request_duration_seconds_bucket;(0.15|0.2|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2|3|3.5|4|4.5|6|7|8|9|15|25|40|50)
                sourceLabels:
                  - __name__
                  - le
              - sourceLabels: [__name__]
                regex: etcd_request_duration_seconds_bucket|apiserver_request_sli_duration_seconds_bucket|kubernetes_feature_enabled|apiserver_request_duration_seconds|storage_operation_duration_seconds_bucket|container_blkio_device_usage_total
                action: drop
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
