apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: zalando
  namespace: part2-zalando
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 3
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    app: # or 'foo_user: []'

  #databases: name->owner
  databases:
    app: app
  postgresql:
    version: "16"