---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: zalando
  namespace: part2-zalando
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 5
  users:
    # database owner
    zalando:
      - superuser
      - createdb

    # role for application foo
    app: # or 'foo_user: []'
    second:
      - superuser

  #databases: name->owner
  databases:
    app: app
    second: second
  postgresql:
    version: "17"
  env:
    - name: AWS_ENDPOINT
      value: my-custom-bucket
    - name: AWS_REGION
      value: eu-frankfurt-1
    - name: WALE_S3_PREFIX
      value: part2-zalando
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: oci-s3-credentials
          key: accessKeyId
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: oci-s3-credentials
          key: secretAccessKey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
  namespace: part2-zalando
data:
  pod_environment_configmap: "part2-zalando/pod-config"
---
# config file with password is outside git
