apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: oci # oracle cloud NFS
  accessModes:
    # This is just dangerous - this will basically created shared network volume (single one) for all the deployments
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi